In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r"cust_satisfaction(in).csv")
df

Gender      Customer Type   Type of Travel     Class  \
0         Male     Loyal Customer  Personal Travel  Eco Plus   
1         Male  disloyal Customer  Business travel  Business   
2       Female     Loyal Customer  Business travel  Business   
3       Female     Loyal Customer  Business travel  Business   
4         Male     Loyal Customer  Business travel  Business   
...        ...                ...              ...       ...   
103899  Female  disloyal Customer  Business travel       Eco   
103900    Male     Loyal Customer  Business travel  Business   
103901    Male  disloyal Customer  Business travel  Business   
103902  Female  disloyal Customer  Business travel       Eco   
103903    Male     Loyal Customer  Business travel  Business   

                   satisfaction  Age  Flight Distance  Inflight entertainment  \
0       neutral or dissatisfied   13              460                       5   
1       neutral or dissatisfied   25              235                       1   
2                     satisfied   26             1142                       5   
3       neutral or dissatisfied   25              562                       2   
4                     satisfied   61              214                       3   
...                         ...  ...              ...                     ...   
103899  neutral or dissatisfied   23              192                       2   
103900                satisfied   49             2347                       5   
103901  neutral or dissatisfied   30             1995                       4   
103902  neutral or dissatisfied   22             1000                       1   
103903  neutral or dissatisfied   27             1723                       1   

        Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                      4            5                          25   
1                      3            1                           1   
2                      4            5                           0   
3                      3            2                          11   
4                      4            3                           0   
...                  ...          ...                         ...   
103899                 4            2                           3   
103900                 5            4                           0   
103901                 4            4                           7   
103902                 1            1                           0   
103903                 4            1                           0   

        Arrival Delay in Minutes  
0                           18.0  
1                            6.0  
2                            0.0  
3                            9.0  
4                            0.0  
...                          ...  
103899                       0.0  
103900                       0.0  
103901                      14.0  
103902                       0.0  
103903                       0.0  

[103904 rows x 12 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103904 non-null  object 
 1   Customer Type               103904 non-null  object 
 2   Type of Travel              103904 non-null  object 
 3   Class                       103904 non-null  object 
 4   satisfaction                103904 non-null  object 
 5   Age                         103904 non-null  int64  
 6   Flight Distance             103904 non-null  int64  
 7   Inflight entertainment      103904 non-null  int64  
 8   Baggage handling            103904 non-null  int64  
 9   Cleanliness                 103904 non-null  int64  
 10  Departure Delay in Minutes  103904 non-null  int64  
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB


In [7]:
df.describe()  # describe function use to describe integer value of the dataset

Age  Flight Distance  Inflight entertainment  \
count  103904.000000    103904.000000           103904.000000   
mean       39.379706      1189.448375                3.358158   
std        15.114964       997.147281                1.332991   
min         7.000000        31.000000                0.000000   
25%        27.000000       414.000000                2.000000   
50%        40.000000       843.000000                4.000000   
75%        51.000000      1743.000000                4.000000   
max        85.000000      4983.000000                5.000000   

       Baggage handling    Cleanliness  Departure Delay in Minutes  \
count     103904.000000  103904.000000               103904.000000   
mean           3.631833       3.286351                   14.815618   
std            1.180903       1.312273                   38.230901   
min            1.000000       0.000000                    0.000000   
25%            3.000000       2.000000                    0.000000   
50%            4.000000       3.000000                    0.000000   
75%            5.000000       4.000000                   12.000000   
max            5.000000       5.000000                 1592.000000   

       Arrival Delay in Minutes  
count             103594.000000  
mean                  15.178678  
std                   38.698682  
min                    0.000000  
25%                    0.000000  
50%                    0.000000  
75%                   13.000000  
max                 1584.000000

In [8]:
df.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
satisfaction                  0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64

In [11]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

In [12]:
df["satisfaction"].unique()

array(['neutral or dissatisfied', 'satisfied'], dtype=object)

In [13]:
df["Customer Type"].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [14]:
dt = { 
    'Loyal Customer' : 1,
    'disloyal Customer' : 0
    
    }

df["Customer Type"]=df["Customer Type"].map(dt)

In [15]:
df["Customer Type"].unique()

array([1, 0], dtype=int64)

In [16]:
df["Type of Travel"].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [17]:
dt1 = {
    'Business travel' : 1,
    'Personal Travel' : 0
}
df["Type of Travel"]=df["Type of Travel"].map(dt1)
df["Type of Travel"].unique()

array([0, 1], dtype=int64)

In [18]:
df["satisfaction"].unique()

array(['neutral or dissatisfied', 'satisfied'], dtype=object)

In [19]:
dt2 = {
    'neutral or dissatisfied' : 1,
    'satisfied' : 0
}
df["satisfaction"]=df['satisfaction'].map(dt2)


In [20]:
df["satisfaction"].unique()

array([1, 0], dtype=int64)

In [21]:
df['Class'].unique()

array(['Eco Plus', 'Business', 'Eco'], dtype=object)

In [22]:
dt3 = { 
    'Eco Plus' : 0,
    'Business' : 1,
    'Eco' : 2
}
df['Class']=df['Class'].map(dt3)

In [23]:
df["Class"].unique()

array([0, 1, 2], dtype=int64)

In [24]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [25]:
dt4 = {
    'Male' : 1,
    'Female' : 0
}
df['Gender']=df['Gender'].map(dt4)

In [26]:
df['Gender'].unique()

array([1, 0], dtype=int64)

In [28]:
df.head()

Gender  Customer Type  Type of Travel  Class  satisfaction  Age  \
0       1              1               0      0             1   13   
1       1              0               1      1             1   25   
2       0              1               1      1             0   26   
3       0              1               1      1             1   25   
4       1              1               1      1             0   61   

   Flight Distance  Inflight entertainment  Baggage handling  Cleanliness  \
0              460                       5                 4            5   
1              235                       1                 3            1   
2             1142                       5                 4            5   
3              562                       2                 3            2   
4              214                       3                 4            3   

   Departure Delay in Minutes  Arrival Delay in Minutes  
0                          25                      18.0  
1                           1                       6.0  
2                           0                       0.0  
3                          11                       9.0  
4                           0                       0.0

In [34]:
df.drop('satisfaction',axis=1)

Gender  Customer Type  Type of Travel  Class  Age  Flight Distance  \
0            1              1               0      0   13              460   
1            1              0               1      1   25              235   
2            0              1               1      1   26             1142   
3            0              1               1      1   25              562   
4            1              1               1      1   61              214   
...        ...            ...             ...    ...  ...              ...   
103899       0              0               1      2   23              192   
103900       1              1               1      1   49             2347   
103901       1              0               1      1   30             1995   
103902       0              0               1      2   22             1000   
103903       1              1               1      1   27             1723   

        Inflight entertainment  Baggage handling  Cleanliness  \
0                            5                 4            5   
1                            1                 3            1   
2                            5                 4            5   
3                            2                 3            2   
4                            3                 4            3   
...                        ...               ...          ...   
103899                       2                 4            2   
103900                       5                 5            4   
103901                       4                 4            4   
103902                       1                 1            1   
103903                       1                 4            1   

        Departure Delay in Minutes  Arrival Delay in Minutes  
0                               25                      18.0  
1                                1                       6.0  
2                                0                       0.0  
3                               11                       9.0  
4                                0                       0.0  
...                            ...                       ...  
103899                           3                       0.0  
103900                           0                       0.0  
103901                           7                      14.0  
103902                           0                       0.0  
103903                           0                       0.0  

[103422 rows x 11 columns]

In [35]:
x = df.drop('satisfaction',axis=1)

y = df['satisfaction']

In [36]:
from sklearn.model_selection import train_test_split


In [55]:
x_train,x_test, y_train, y_test= train_test_split(x,y , test_size=0.2, random_state= 42)


In [56]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape


((82737, 11), (20685, 11), (82737,), (20685,))

In [57]:
x_test

Gender  Customer Type  Type of Travel  Class  Age  Flight Distance  \
40794       1              1               1      1   38             2623   
28574       0              1               1      1   50             1617   
4920        1              1               1      0   72              270   
71169       0              1               1      1   45             1998   
67168       1              1               1      1   39             2153   
...       ...            ...             ...    ...  ...              ...   
78398       0              0               1      1   22              937   
47803       1              1               1      2   47              956   
69942       0              1               1      1   25             1576   
6464        0              1               0      2   24              622   
49721       0              1               0      2   56              821   

       Inflight entertainment  Baggage handling  Cleanliness  \
40794                       4                 4            1   
28574                       5                 5            4   
4920                        1                 4            1   
71169                       5                 4            4   
67168                       5                 5            5   
...                       ...               ...          ...   
78398                       5                 3            5   
47803                       5                 4            5   
69942                       1                 4            1   
6464                        4                 4            4   
49721                       2                 2            1   

       Departure Delay in Minutes  Arrival Delay in Minutes  
40794                           0                       0.0  
28574                           6                      14.0  
4920                            6                       0.0  
71169                           0                       0.0  
67168                           0                       7.0  
...                           ...                       ...  
78398                           5                      12.0  
47803                           0                       0.0  
69942                           0                       0.0  
6464                            0                       0.0  
49721                           0                       0.0  

[20685 rows x 11 columns]

In [58]:
y_test

40794    0
28574    0
4920     1
71169    0
67168    0
        ..
78398    0
47803    0
69942    1
6464     1
49721    1
Name: satisfaction, Length: 20685, dtype: int64

In [42]:
from sklearn.linear_model import LinearRegression


In [43]:
lr = LinearRegression()

In [44]:
lr.fit(x_train,y_train)

LinearRegression()

In [45]:
print("traning score :-", lr.score(x_train,y_train))


traning score :- 0.43486130222404407


In [53]:
print("testing score :-", lr.score(x_test,y_test))


testing score :- 0.4370163241034968


In [47]:
pred =lr.predict(x_test)


In [48]:
pred

array([0.33329263, 0.10312993, 0.47118366, ..., 0.50508032, 0.79270261,
       1.15593946])

In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
dt_obj = DecisionTreeClassifier(criterion='entropy')

In [52]:
dt_obj.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [59]:
dt_obj.score(x_train,y_train)

0.9996736647449146

In [61]:
dt_obj.score(x_test,y_test)

0.8189992748368383

In [64]:
y_test=pd.DataFrame(y_test)

In [66]:
y_test

satisfaction
40794             0
28574             0
4920              1
71169             0
67168             0
...             ...
78398             0
47803             0
69942             1
6464              1
49721             1

[20685 rows x 1 columns]

In [67]:
# dt_obj.predict(y_test)
dt_obj.predict(x_test)

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [69]:
y_test

satisfaction
40794             0
28574             0
4920              1
71169             0
67168             0
...             ...
78398             0
47803             0
69942             1
6464              1
49721             1

[20685 rows x 1 columns]

In [68]:
x_test

Gender  Customer Type  Type of Travel  Class  Age  Flight Distance  \
40794       1              1               1      1   38             2623   
28574       0              1               1      1   50             1617   
4920        1              1               1      0   72              270   
71169       0              1               1      1   45             1998   
67168       1              1               1      1   39             2153   
...       ...            ...             ...    ...  ...              ...   
78398       0              0               1      1   22              937   
47803       1              1               1      2   47              956   
69942       0              1               1      1   25             1576   
6464        0              1               0      2   24              622   
49721       0              1               0      2   56              821   

       Inflight entertainment  Baggage handling  Cleanliness  \
40794                       4                 4            1   
28574                       5                 5            4   
4920                        1                 4            1   
71169                       5                 4            4   
67168                       5                 5            5   
...                       ...               ...          ...   
78398                       5                 3            5   
47803                       5                 4            5   
69942                       1                 4            1   
6464                        4                 4            4   
49721                       2                 2            1   

       Departure Delay in Minutes  Arrival Delay in Minutes  
40794                           0                       0.0  
28574                           6                      14.0  
4920                            6                       0.0  
71169                           0                       0.0  
67168                           0                       7.0  
...                           ...                       ...  
78398                           5                      12.0  
47803                           0                       0.0  
69942                           0                       0.0  
6464                            0                       0.0  
49721                           0                       0.0  

[20685 rows x 11 columns]

In [73]:
import joblib  as jb

In [74]:
jb.dump(dt_obj,'loyal_data.lb')

['loyal_data.lb']

In [75]:
model = jb.load('loyal_data.lb')

In [77]:
model.predict(x_test)

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)