In [92]:
# pip install numpy

In [93]:
# %pip install numpy

In [121]:
import numpy as np
print("Numpy successfully imported")

Numpy successfully imported


In [95]:
lst = list(range(1,25))

In [96]:
lst

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [97]:
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [98]:
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [99]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [100]:
arr2 = np.array([1,2,5,"jhg",3,8,9,7])

In [101]:
print(arr2)
print(type(arr2))

['1' '2' '5' 'jhg' '3' '8' '9' '7']
<class 'numpy.ndarray'>


In [102]:
lst1 = [1651,'hello',2.35,True]

In [103]:
print(lst1)

[1651, 'hello', 2.35, True]


In [104]:
arr3 = np.arange(1,25)   # used to create array with range 
print(arr3)   # 1D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [105]:
# 2D array of 0's
arr = np.zeros((3,4))   # Creating a 2D array using zeros(())
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
arr = np.array([[156,454,4],[654,351,98]])   # 2D array
arr

array([[156, 454,   4],
       [654, 351,  98]])

In [107]:
# 3D array
arr = np.array([[[1,2,3,4],[9,8,7,4],[654,541,43,8]],[[6541,6541,321,646],[654,64,132,151],[6544,654,748,1]]])
arr

array([[[   1,    2,    3,    4],
        [   9,    8,    7,    4],
        [ 654,  541,   43,    8]],

       [[6541, 6541,  321,  646],
        [ 654,   64,  132,  151],
        [6544,  654,  748,    1]]])

In [108]:
ar = np.array([[[65156,61,16,51],[654,464,164,1],[654,644,164,3]]])
ar

array([[[65156,    61,    16,    51],
        [  654,   464,   164,     1],
        [  654,   644,   164,     3]]])

In [109]:
arrr = np.ones((3,4)) # 2D array of 1's
arrr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [110]:
ar = np.linspace(1,10,5)   # 1 to 10 ke bich 5 values hongi
ar

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [111]:
ar = np.linspace(1,10,5).reshape(5,1)    # ar.reshape(5,1)
ar

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [112]:
ar = np.arange(0,30)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [113]:
print(ar.reshape(5,6))
ar.reshape(3,5,2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [114]:
ar.shape

(30,)

In [115]:
arr = np.random.randint(1,5,9)   # generates 9 random numers b/w 1 to 5
arr

array([3, 4, 2, 2, 3, 2, 2, 3, 4])

In [116]:
arr = np.random.randint(1,5,(3,10))  # generates 3x10 matrix b/w 1 to 5
arr

array([[2, 4, 3, 2, 1, 4, 3, 4, 3, 2],
       [1, 4, 2, 4, 1, 3, 4, 4, 4, 1],
       [2, 1, 2, 2, 3, 2, 3, 2, 4, 1]])

In [117]:
arr = np.random.randint(1,5,(3,4,5))  # generates 3x4x5 matrix b/w 1 to 5
arr

array([[[2, 2, 1, 3, 3],
        [1, 4, 2, 3, 1],
        [3, 2, 4, 3, 2],
        [2, 4, 2, 3, 1]],

       [[1, 4, 2, 2, 2],
        [2, 2, 4, 1, 2],
        [3, 2, 4, 3, 1],
        [4, 4, 1, 2, 2]],

       [[2, 3, 2, 4, 4],
        [2, 2, 1, 1, 3],
        [2, 2, 1, 4, 1],
        [4, 1, 2, 4, 4]]])

In [118]:
arr = np.random.random(10)   # random array of 10 b/w  0 to 1
arr

array([0.27194354, 0.21596625, 0.15501042, 0.5526784 , 0.63895671,
       0.45003665, 0.51656616, 0.22857295, 0.76557852, 0.74509744])

In [119]:
arr = np.random.randint(10)   # random array of only 1 b/w  0 to 10   by default only one value it gives
arr


8

In [120]:
arr = np.random.randint(-10)   # -ve is not valid
arr

ValueError: high <= 0

In [ ]:
arr = np.random.random((3,4,5))   # random array of only 1 b/w  0 to 10   by default only one value it gives
print(arr)


[[[0.41319409 0.96793904 0.78791551 0.60207854 0.94349378]
  [0.73738279 0.31895906 0.03644853 0.41811157 0.22918563]
  [0.25566368 0.34217143 0.70507039 0.56587143 0.65999288]
  [0.17586746 0.31497732 0.37136723 0.72646372 0.28831784]]

 [[0.21652614 0.35948595 0.06668421 0.15720183 0.93126386]
  [0.54374367 0.14010246 0.02643312 0.39280748 0.08034971]
  [0.12095683 0.12364174 0.1876326  0.66120955 0.90648581]
  [0.18326529 0.03023657 0.15666204 0.76292236 0.55685313]]

 [[0.41913146 0.26363976 0.23263939 0.47829733 0.37692484]
  [0.64997598 0.13102623 0.5647312  0.18416679 0.3350587 ]
  [0.98674386 0.16583457 0.92700691 0.67825852 0.40175264]
  [0.08228286 0.54808077 0.43788599 0.19098483 0.74126354]]]


In [ ]:
arr = np.arange(60).reshape(10,6)
print(arr)
arr.dtype


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [ ]:
print(arr.ndim)  # dimension of array
print(arr.size)    # total elements in array
print(arr.shape)    # (row,columns) in array

2
60
(10, 6)


In [ ]:
arr.flatten()    # 2D to 1D array conversion

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.ravel()  # convert 3D or 2D to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
ls = [654,351,658,"jg"]
ar1 = np.array(ls)

In [ ]:
ar1

array(['654', '351', '658', 'jg'], dtype='<U11')

In [ ]:
ar1.dtype  # print the type of array

dtype('<U11')

In [ ]:
ar1.T.shape # Transpose/reverse the shape of array

(4,)

In [ ]:
ls = [[1,2,3],[5,4,6]]
arr = np.array(ls)
arr

array([[1, 2, 3],
       [5, 4, 6]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.T

array([[1, 5],
       [2, 4],
       [3, 6]])

In [ ]:
arr.T.shape

(3, 2)

Slicing

In [122]:
arr = np.array([1,64,1,47,1451,16,843,345,1,54,537,53,6])
arr

array([   1,   64,    1,   47, 1451,   16,  843,  345,    1,   54,  537,
         53,    6])

In [123]:
arr[3:11]

array([  47, 1451,   16,  843,  345,    1,   54,  537])

In [ ]:
lst = list(range(1,100))
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [125]:
arr[5:60]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60])

In [129]:
arr[0:22:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [133]:
arr = arr.reshape(33,3)

In [139]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48],
       [49, 50, 51],
       [52, 53, 54],
       [55, 56, 57],
       [58, 59, 60],
       [61, 62, 63],
       [64, 65, 66],
       [67, 68, 69],
       [70, 71, 72],
       [73, 74, 75],
       [76, 77, 78],
       [79, 80, 81],
       [82, 83, 84],
       [85, 86, 87],
       [88, 89, 90],
       [91, 92, 93],
       [94, 95, 96],
       [97, 98, 99]])

In [134]:
arr[0:5]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
arr[0:5,1:2]  # 2nd column printing

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [ ]:
arr[2,2]    # Particular element find from matrix

9

In [ ]:
arr[-1][-1]  # array ka last element print hoga

99

In [140]:
arr[ :4][-1]

array([10, 11, 12])

In [141]:
arr[3,1] = 123
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10, 123,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [ 25,  26,  27],
       [ 28,  29,  30],
       [ 31,  32,  33],
       [ 34,  35,  36],
       [ 37,  38,  39],
       [ 40,  41,  42],
       [ 43,  44,  45],
       [ 46,  47,  48],
       [ 49,  50,  51],
       [ 52,  53,  54],
       [ 55,  56,  57],
       [ 58,  59,  60],
       [ 61,  62,  63],
       [ 64,  65,  66],
       [ 67,  68,  69],
       [ 70,  71,  72],
       [ 73,  74,  75],
       [ 76,  77,  78],
       [ 79,  80,  81],
       [ 82,  83,  84],
       [ 85,  86,  87],
       [ 88,  89,  90],
       [ 91,  92,  93],
       [ 94,  95,  96],
       [ 97,  98,  99]])

In [146]:
arr = np.arange(0,30).reshape(3,5,2)

In [147]:
arr[0][2:7]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [149]:
arr[: , 0:1, 0:1]

array([[[ 0]],

       [[10]],

       [[20]]])

In [159]:
x = list(range(0,5))
y = list(range(3,8))

print(x)
print(y)

print(x+y)

[0, 1, 2, 3, 4]
[3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 3, 4, 5, 6, 7]


In [160]:
arr1 = np.array(x)
arr2 = np.array(y)

print(arr1)
print(arr2)
# print(arr1 + arr2)

[0 1 2 3 4]
[3 4 5 6 7]


In [161]:
arr1 + arr2

array([ 3,  5,  7,  9, 11])

In [162]:
print(x*y)

TypeError: can't multiply sequence by non-int of type 'list'

In [163]:
arr1 * arr2

array([ 0,  4, 10, 18, 28])