In [ ]:
# pip install numpy

In [ ]:
# %pip install numpy

In [2]:
import numpy as np
print("Numpy successfully imported")

Numpy successfully imported


In [3]:
lst = list(range(1,25))

In [4]:
lst

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [6]:
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [9]:
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [10]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [15]:
arr2 = np.array([1,2,5,"jhg",3,8,9,7])

In [17]:
print(arr2)
print(type(arr2))

['1' '2' '5' 'jhg' '3' '8' '9' '7']
<class 'numpy.ndarray'>


In [13]:
lst1 = [1651,'hello',2.35,True]

In [14]:
print(lst1)

[1651, 'hello', 2.35, True]


In [20]:
arr3 = np.arange(1,25)   # used to create array with range 
print(arr3)   # 1D array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
# 2D array of 0's
arr = np.zeros((3,4))   # Creating a 2D array using zeros(())
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.array([[156,454,4],[654,351,98]])   # 2D array
arr

array([[156, 454,   4],
       [654, 351,  98]])

In [30]:
# 3D array
arr = np.array([[[1,2,3,4],[9,8,7,4],[654,541,43,8]],[[6541,6541,321,646],[654,64,132,151],[6544,654,748,1]]])
arr

array([[[   1,    2,    3,    4],
        [   9,    8,    7,    4],
        [ 654,  541,   43,    8]],

       [[6541, 6541,  321,  646],
        [ 654,   64,  132,  151],
        [6544,  654,  748,    1]]])

In [32]:
ar = np.array([[[65156,61,16,51],[654,464,164,1],[654,644,164,3]]])
ar

array([[[65156,    61,    16,    51],
        [  654,   464,   164,     1],
        [  654,   644,   164,     3]]])

In [ ]:
arrr = np.ones((3,4)) # 2D array of 1's
arrr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
ar = np.linspace(1,10,5)   # 1 to 10 ke bich 5 values hongi
ar

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
ar = np.linspace(1,10,5).reshape(5,1)    # ar.reshape(5,1)
ar

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [50]:
ar = np.arange(0,30)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
print(ar.reshape(5,6))
ar.reshape(3,5,2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [52]:
ar.shape

(30,)

In [ ]:
arr = np.random.randint(1,5,9)   # generates 9 random numers b/w 1 to 5
arr

array([3, 4, 1, 2, 4, 2, 1, 1, 4])

In [ ]:
arr = np.random.randint(1,5,(3,10))  # generates 3x10 matrix b/w 1 to 5
arr

array([[4, 3, 4, 3, 2, 3, 2, 1, 1, 3],
       [4, 1, 1, 3, 2, 4, 3, 2, 3, 2],
       [4, 2, 1, 4, 4, 3, 4, 1, 4, 1]])

In [62]:
arr = np.random.randint(1,5,(3,4,5))  # generates 3x4x5 matrix b/w 1 to 5
arr

array([[[1, 3, 4, 4, 2],
        [1, 4, 1, 1, 1],
        [3, 4, 1, 1, 4],
        [1, 4, 4, 4, 2]],

       [[4, 4, 1, 3, 2],
        [1, 3, 3, 4, 1],
        [1, 3, 3, 1, 1],
        [4, 2, 1, 3, 2]],

       [[3, 1, 4, 4, 1],
        [3, 2, 1, 4, 2],
        [1, 4, 1, 3, 3],
        [1, 3, 3, 3, 2]]])

In [ ]:
arr = np.random.random(10)   # random array of 10 b/w  0 to 1
arr

array([0.97050447, 0.3043574 , 0.81228065, 0.53052459, 0.80360806,
       0.17337251, 0.41839381, 0.71258276, 0.86660442, 0.19257434])

In [ ]:
arr = np.random.randint(10)   # random array of only 1 b/w  0 to 10   by default only one value it gives
arr


4

In [ ]:
arr = np.random.randint(-10)   # -ve is not valid
arr

ValueError: high <= 0

In [ ]:
arr = np.random.random((3,4,5))   # random array of only 1 b/w  0 to 10   by default only one value it gives
print(arr)


[[[0.41319409 0.96793904 0.78791551 0.60207854 0.94349378]
  [0.73738279 0.31895906 0.03644853 0.41811157 0.22918563]
  [0.25566368 0.34217143 0.70507039 0.56587143 0.65999288]
  [0.17586746 0.31497732 0.37136723 0.72646372 0.28831784]]

 [[0.21652614 0.35948595 0.06668421 0.15720183 0.93126386]
  [0.54374367 0.14010246 0.02643312 0.39280748 0.08034971]
  [0.12095683 0.12364174 0.1876326  0.66120955 0.90648581]
  [0.18326529 0.03023657 0.15666204 0.76292236 0.55685313]]

 [[0.41913146 0.26363976 0.23263939 0.47829733 0.37692484]
  [0.64997598 0.13102623 0.5647312  0.18416679 0.3350587 ]
  [0.98674386 0.16583457 0.92700691 0.67825852 0.40175264]
  [0.08228286 0.54808077 0.43788599 0.19098483 0.74126354]]]


In [78]:
arr = np.arange(60).reshape(10,6)
print(arr)
arr.dtype


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [ ]:
print(arr.ndim)  # dimension of array
print(arr.size)    # total elements in array
print(arr.shape)    # (row,columns) in array

2
60
(10, 6)


In [ ]:
arr.flatten()    # 2D to 1D array conversion

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [81]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [82]:
ls = [654,351,658,"jg"]
ar1 = np.array(ls)

In [83]:
ar1

array(['654', '351', '658', 'jg'], dtype='<U11')

In [ ]:
ar1.dtype  # print the type of array

dtype('<U11')

In [ ]:
ar1.T.shape # Transpose/reverse the shape of array

(4,)

In [86]:
ls = [[1,2,3],[5,4,6]]
arr = np.array(ls)
arr

array([[1, 2, 3],
       [5, 4, 6]])

In [89]:
arr.shape

(2, 3)

In [87]:
arr.T

array([[1, 5],
       [2, 4],
       [3, 6]])

In [88]:
arr.T.shape

(3, 2)