In [1]:
import numpy as np

In [2]:
lst = [1,25,7,8,94]

In [3]:
arr=np.array(lst)

In [4]:
arr

array([ 1, 25,  7,  8, 94])

In [6]:
lst = list(range(1,25))
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [7]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr = np.random.randint(1,5,(3,3))  # random elements b/w 1 to 5 in 3x3 matrix format
arr

array([[3, 2, 2],
       [3, 4, 4],
       [1, 2, 3]])

In [ ]:
arr = np.random.random(10)  # 10 Random numbers 
arr

array([0.43623163, 0.23486089, 0.63638535, 0.35604656, 0.09782719,
       0.96636686, 0.67562072, 0.14993951, 0.35137286, 0.32769563])

In [17]:
arr.shape

(10,)